### ISSUE TITLE
Move openmHealth folder to Preprocessing repo

### ISSUE THREAD

**Issue by brinnaebent** [DigitalBiomarkerDiscoveryPipeline/Data-Compression-Toolbox#3]
@GeetikaSi @BaiyingLu can we please move the OpenmHealth repo to the Preprocessing repo? It should not be here! Thanks!

**Comment by BaiyingLu** [comment]
The code of OpenmHealth part has been integrated into the Preprocessing repo, and the original folder here has been removed
